### ISSUE TITLE
start up error

### ISSUE THREAD

**Issue by stardrom** [jakedent/seo-bot-python#1]
Hi when i run the script, i get the error below:
Proxy == Local Host at 127.0.0.1 port 9150.
Secure Socket Layer initialized with PySocks ...
Traceback (most recent call last):

  File "seobot.py", line 34, in <module>
    ip_switch()
  File "seobot.py", line 25, in ip_switch
    with Controller.from_port(port=9151) as controller:
  File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 1021, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 493, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 176, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 528, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

**Comment by jakedent** [comment]
No worries, I hope this is a simple fix : https://jacobdent.com/blog/search-engine-optimisation-bot

Scroll down to the first header of 'Lets go' and follow the screenshots for setting the ports for localhost in Tor. 

Hope that helps.

**Comment by anyaozm** [comment]
Hi Jake! Awesome code. I had the same issue and the blog post seems to be unavailable. Could you point me to the right direction please?

**Comment by jakedent** [comment]
Hi Anyaozm. Thanks for the nice comment. Apologies for the delay, have been busy with work. I need to find the blog post (old machine & old domain) to provide the exact instructions.

For now, please try: 
1) Click menu and hit "Preferences..."
2) Click custom proxy settings"
3) Edit socks port to 9051 and configure proxy as localhost.
4) Hit OK. 

Hope this helps. Cheers.
